version: 2
updates:
  - package-ecosystem: "pip" # For Python projects using pip
    directory: "/" # Location of the dependency files
    schedule:
      interval: "weekly" # Check for updates weekly
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns:
          - ".*"
